import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

global java.util.HashMap resMap;


// 规则1:
rule "Age based discount11"
    when
        (Map(this["product_id"]  == null))
    then
        resMap.put(drools.getRule().getName(), "product_id is null");
end

// 规则2：
rule "Customer type based discount - Loyal customer22"
    when
        (Map(this["product_id"]  != null))
    then
        System.out.println("=>>>>>>" + drools.getRule().getName());
        resMap.put(drools.getRule().getName(), "product_id is not null");
end

rule "Customer type based discount - others333"
    when
    (Map(this["order_id"]  != null))
    then
    resMap.put(drools.getRule().getName(), "order_id is not null");
end

rule "Amount based discount444"
    when
    (Map(this["order_id"]  == 1))
    then
    resMap.put(drools.getRule().getName(), "order_id is one");
end
